# Generated by Django 6.0.1 on 2026-02-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imovel_contrato_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='valor_aluguek',
            new_name='valor_aluguel',
        ),
    ]
