# Generated by Django 6.0.1 on 2026-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_valor_aluguek_imovel_valor_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='titulo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
